export const HOME_ROUTE = '/'
export const ABOUT_ROUTE = '/about'
export const HELP_ROUTE = '/help'
export const NOT_FOUND_ROUTE = '/not-found'
export const DENLOVE_GITHUB_ROUTE = 'https://github.com/denlove'
