name: Development

on:
    pull_request:
        branches:
            - master
        types:
            - opened
            - edited
            - synchronize
            - reopened
    workflow_call:

concurrency:
    group: ${{ github.head_ref }}
    cancel-in-progress: true

jobs:
    install-cache:
        name: Install and cache deps
        runs-on: ubuntu-latest
        timeout-minutes: 2
        strategy:
            matrix:
                node-version: [20]
        steps:
            - name: 🔦 Checkout repository
              uses: actions/checkout@v4

            - name: 🔧 Setup NodeJS v${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: 📦 Cache yarn dependencies
              uses: actions/cache@v4
              id: cache-dependencies
              with:
                  path: node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: 💡 Install Dependencies
              if: steps.cache-dependencies.outputs.cache-hit != 'true'
              run: yarn install --force --non-interactive

    test:
        name: Testing stage
        runs-on: ubuntu-latest
        timeout-minutes: 2
        needs: install-cache
        strategy:
            matrix:
                node-version: [20]
        steps:
            - name: 🔦 Checkout repository
              uses: actions/checkout@v4

            - name: 🔧 Setup NodeJS v${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: 📦 Restore yarn dependencies
              uses: actions/cache@v4
              id: cache-dependencies
              with:
                  path: node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: 🔍 Test code
              run: yarn test

    lint:
        name: Linting stage
        runs-on: ubuntu-latest
        timeout-minutes: 2
        needs: install-cache
        strategy:
            matrix:
                node-version: [20]
        steps:
            - name: 🔦 Checkout repository
              uses: actions/checkout@v4

            - name: 🔧 Setup NodeJS v${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: 📦 Restore yarn dependencies
              uses: actions/cache@v4
              id: cache-dependencies
              with:
                  path: node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: 🔍 Lint code
              run: yarn lint
